# Generated by Django 3.2.13 on 2022-04-26 13:16

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='agents_opinions',
            field=wagtail.core.fields.StreamField([('AgentsBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agents_opinions_ar',
            field=wagtail.core.fields.StreamField([('AgentsBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agents_opinions_en',
            field=wagtail.core.fields.StreamField([('AgentsBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_banner',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Banner title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  Banner description')), ('images', wagtail.core.blocks.ListBlock(home.blocks.BannerImageBlock))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_banner_ar',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Banner title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  Banner description')), ('images', wagtail.core.blocks.ListBlock(home.blocks.BannerImageBlock))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_banner_en',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Banner title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  Banner description')), ('images', wagtail.core.blocks.ListBlock(home.blocks.BannerImageBlock))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_data',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_data_ar',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_data_en',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon'))]))], blank=True, null=True),
        ),
    ]
