# Generated by Django 3.2.13 on 2022-04-28 08:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220426_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_banner',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_banner_ar',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_banner_en',
            field=wagtail.core.fields.StreamField([('BannerBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_data',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_data_ar',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_data_en',
            field=wagtail.core.fields.StreamField([('HomeDataBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
    ]
