# Generated by Django 3.2.13 on 2022-04-26 12:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='City Name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('intro_text', models.TextField(verbose_name='Introduction Text')),
                ('intro_text_en', models.TextField(null=True, verbose_name='Introduction Text')),
                ('intro_text_ar', models.TextField(null=True, verbose_name='Introduction Text')),
                ('description', wagtail.core.fields.RichTextField(verbose_name='Description')),
                ('description_en', wagtail.core.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ar', wagtail.core.fields.RichTextField(null=True, verbose_name='Description')),
                ('show_in_home', models.BooleanField(default=False, verbose_name='Show in home')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouristPlaceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('tourist_place', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_images', to='tourist_sites.touristplace')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
