# Generated by Django 3.2.13 on 2022-05-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_sites', to='tourist_sites.city'),
            preserve_default=False,
        ),
    ]
