# Generated by Django 3.2.13 on 2022-04-30 14:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('organization_tagline', models.CharField(max_length=100, verbose_name='Organization tagline')),
                ('customer_service', wagtail.core.fields.StreamField([('CustomerServiceBlock', wagtail.core.blocks.StructBlock([('phone', wagtail.core.blocks.CharBlock(help_text='Add phone number', max_length=20)), ('email', wagtail.core.blocks.EmailBlock(help_text='Add email')), ('address', wagtail.core.blocks.CharBlock(help_text='Add address', max_length=300))]))], blank=True, null=True)),
                ('footer_links', wagtail.core.fields.StreamField([('FooterMenuBlock', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link ', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add internal page only', required=False))]))], blank=True, null=True)),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='About us text')),
                ('copyright_text', models.CharField(default='All rights reserved', max_length=255, verbose_name='Copyright Text')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_logo', related_query_name='+', to='wagtailimages.image')),
                ('logo_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_logo', related_query_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
