# Generated by Django 3.2.13 on 2022-05-10 08:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('main_content', wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True)),
                ('main_content_en', wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True)),
                ('main_content_ar', wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True)),
                ('principle', wagtail.core.fields.StreamField([('PrincipleBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True)),
                ('principle_en', wagtail.core.fields.StreamField([('PrincipleBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True)),
                ('principle_ar', wagtail.core.fields.StreamField([('PrincipleBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True)),
                ('our_team', wagtail.core.fields.StreamField([('OurTeamBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True)),
                ('our_team_en', wagtail.core.fields.StreamField([('OurTeamBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True)),
                ('our_team_ar', wagtail.core.fields.StreamField([('OurTeamBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add agent name', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add agent opinion')), ('avatar', wagtail.images.blocks.ImageChooserBlock(help_text='Add avatar')), ('job', wagtail.core.blocks.CharBlock(max_length=255, required=False))]))], blank=True, null=True)),
                ('best_travel', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
                ('best_travel_en', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
                ('best_travel_ar', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
                ('public_relation', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
                ('public_relation_en', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
                ('public_relation_ar', wagtail.core.fields.StreamField([('BestTravelBlock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.TextBlock(help_text='Add description'))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
