# Generated by Django 3.2.13 on 2022-05-12 11:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='main_content',
            field=wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='main_content_ar',
            field=wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='main_content_en',
            field=wagtail.core.fields.StreamField([('MainContent', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', max_length=255)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Add  description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add icon, image'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='public_relation',
            field=wagtail.core.fields.StreamField([('PublicRelation', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='public_relation_ar',
            field=wagtail.core.fields.StreamField([('PublicRelation', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='public_relation_en',
            field=wagtail.core.fields.StreamField([('PublicRelation', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add link title', max_length=255)), ('external_url', wagtail.core.blocks.CharBlock(help_text='Add External link or internal page only', required=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Add External link or internal page only', required=False))]))], blank=True, null=True),
        ),
    ]
